### ISSUE TITLE
AmazonIVSPlayer fails to compile -- missing required architecture

### ISSUE THREAD

**Issue by esilverberg** [aws-samples/amazon-ivs-player-ios-sample#10]
When attempting to upgrade AmazonIVSPlayer in my project to version 1.2.0, I see the following error:

```
missing required architecture x86_64
```

It compiles just fine when I keep it at version 1.1.0.

**Comment by CFKevinRef** [comment]
Thanks for the report. Where are you seeing this error specifically? For some background, please provide:

1. The output of `bundle exec pod env`
1. The build output, exported by:
   1. Showing the report navigator<br><img width="453" alt="image" src="https://user-images.githubusercontent.com/1749626/103247294-4249a780-491b-11eb-9bf6-f3b06a0cb2ca.png">
   1. Selecting the build that failed<br><img width="289" alt="image" src="https://user-images.githubusercontent.com/1749626/103247342-6c02ce80-491b-11eb-8e10-5eec1d55a108.png">
   1. Clicking the "Export..." button, saving to a file or the clipboard<br><img width="680" alt="image" src="https://user-images.githubusercontent.com/1749626/103247490-e92e4380-491b-11eb-863b-696ac6ecb598.png">

**Comment by CFKevinRef** [comment]
I'm going to close this for now, please reopen if the issue persists.

**Comment by PomegranateApps** [comment]
I'm having this same issue. Is there a solution to fix it?

**Comment by CFKevinRef** [comment]
This issue was not reproduced. Please see the previous comment on how to collect information about your environment so we can help.

**Comment by RasheshAccenture** [comment]
I am getting this error in M1 MacBook Pro.

![image](https://user-images.githubusercontent.com/95026534/146212628-d2ba87f6-a2dd-481e-b9ea-6e96f31953ab.png)

[Build target Test_2021-12-15T20-38-45.txt](https://github.com/aws-samples/amazon-ivs-player-ios-sample/files/7720621/Build.target.Test_2021-12-15T20-38-45.txt)

I have attached a build error log file.
Can you please resolve this?
