### ISSUE TITLE
Picture in Picture support

### ISSUE THREAD

**Issue by hvsw** [aws-samples/amazon-ivs-player-ios-sample#23]
Does IVS supports Picture in Picture?

From [Apple docs](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_custom_player#overview), `AVPictureInPictureController` needs a reference to AVPlayerLayer. I see `IVSPlayer.playerLayer` but that's an `IVSPlayerLayer`, which inherits from `CALayer` and not `AVPlayerLayer`.

I've been using IVS player iOS sample and testing things to go around this problem, like instantiating an AVPlayerLayer(layer: IVSPlayer.playerLayer) but no luck so far...

**Comment by ryanecrist** [comment]
Hello, thanks for filing an issue. Unfortunately at this time the Amazon IVS Player SDK for iOS does not support PiP. This is a feature that we plan on supporting in a future release. Thanks!

**Comment by hvsw** [comment]
Thanks for the reply @ryanecrist. Do you guys have a roadmap/ETA for this?

**Comment by ryanecrist** [comment]
@hvsw PiP support is under active development, but we do not have a specific timeline as to when it will be publicly available yet.

**Comment by ryanecrist** [comment]
Hello @hvsw, wanted to follow up that Picture in Picture support has been added to the Amazon IVS Player SDK for iOS (requires iOS 15 and later). Thanks!
