### ISSUE TITLE
Simulator Video Playback - Xcode 12 beta 5 

### ISSUE THREAD

**Issue by WayneEld** [aws-samples/amazon-ivs-player-ios-sample#3]
Hi there. This may be Xcode beta issue but I think you should be aware of the feedback. When running the sample "Basic Playback" project in the simulator there is no video just audio on the simulated device. This is present in Xcode 12 beta 5, iPhone 11. The video for the sample project works on a real device.

**Comment by CFKevinRef** [comment]
Hi, thanks for the report. I've seen this behavior as well. Simulator A/V has improved dramatically over the last few betas, but unfortunately this particular issue persists.

Would you mind sharing your macOS version as well? I plan to file a radar with Apple for the underlying issue. I'll provide a link here and we can keep this issue open.

**Comment by WayneEld** [comment]
Thanks very much. I am working off Mac Catalina version 10.15.6. I can confirm that this behaviour persists on Xcode 12 beta 6.

**Comment by CFKevinRef** [comment]
We've since tweaked the decoder settings for better compatibility of decoded frames, and this resolves the beta simulator black frame issue. This will be part of the next SDK release.
