### ISSUE TITLE
Picture in Picture support on ios 13 devices

### ISSUE THREAD

**Issue by ckacmaz-clickmelive** [aws-samples/amazon-ivs-player-ios-sample#30]
Hello,
Will it be possible  in the future to support ios 13 devices for picture in picture?

**Comment by ryanecrist** [comment]
Hello, thanks for filing an issue. Unfortunately at this time the Picture in Picture feature of the Amazon IVS Player SDK for iOS is only available on devices running iOS 15 and later. Thanks!
