### ISSUE TITLE
Player duration for VoD asset is indefinite

### ISSUE THREAD

**Issue by joel9stars** [aws-samples/amazon-ivs-player-ios-sample#4]
Hello,

While attempting to play a sample url on the player, the player duration comes up as indefinite (even though it was a 2.43 min video). I have tried other urls as well; some worked and some have the same issue. 

I tried the same url with AVPlayerViewController, and it showed the correct duration. What could be the issue?

Here's the url that I was testing - "https://d21vl8honu7aek.cloudfront.net/out/v1/1dde3e1d23044b4d9900d57443bc5f13/81c00c1f1558463fb095b5405d64b50b/d361d2b4d13a479f829f916983e72e6a/index.m3u8"

**Comment by CFKevinRef** [comment]
What's the source of this stream? We can't commit to supporting arbitrary streams at the moment, but we're looking into the behavior of this one for the sake of player robustness.

**Comment by joel9stars** [comment]
Sorry, I am unable to dig out the source, but the player has this issue with a lot of other HLS .m3u8 streams too. I was intending to use this player for a music video streaming app that my company is building, without using the IVS service.  The streaming would include both live and VoD assets. While attempting to play a 2 hour music concert video, the player duration came out indefinite. 

This link - https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8 - that I picked from [https://bitmovin.com/mpeg-dash-hls-examples-sample-streams/](url) doesn't work as expected either. The player duration gets inferred as indefinite, and the video plays only from the last 15 seconds. This works without an issue on AVPlayerViewController.

**Comment by CFKevinRef** [comment]
I'm going to close the issue since officially we're supporting IVS streams only at this time. I appreciate you bringing this to our attention.
