### ISSUE TITLE
Unable to capture live stream screenshot using IVSPlayer class

### ISSUE THREAD

**Issue by cemnisan** [aws-samples/amazon-ivs-player-ios-sample#45]
I am using the IVSPlayer class to display a live stream in my iOS app. I want to capture a screenshot of the live stream when a button is pressed, but I have been unable to find a way to do so. The screenshot should only represent the live stream view, not any other views. I have tried several approaches but none of them have worked. Can you please provide guidance on how to capture a screenshot of the live stream using the IVSPlayer class?

**Comment by ryanecrist** [comment]
Hello, thanks for filing an issue.

Unfortunately this is not possible with the current version of our iOS player SDK, but is something that we're investigating internally for a future release. A possible workaround is to use [ReplayKit](https://developer.apple.com/documentation/replaykit?language=objc), but this may not fit your intended use case.
