### ISSUE TITLE
ITMS-90338: Non-public API usage : _CMTimebaseCreateWithMasterClock

### ISSUE THREAD

**Issue by hassanabidpk** [aws-samples/amazon-ivs-player-ios-sample#51]
**Describe the bug**
Apple is reporting ITMS-90338: Non-public API usage : _CMTimebaseCreateWithMasterClock in Frameworks/AmazonIVSPlayer.framework/AmazonIVSPlayer. It seems as this is still used by latest version of IVSPlayer SDK

**To Reproduce**
1. Use IVSPlayer version 1.19.0 
2. Build app and publish to Test flight on appstore

**Expected behavior**
Apple has implemented their guidelines for Non-public API usage. It seems as IVSPlayer is using a private API hence apple is blocking appstore submission

**Screenshots**
N/A

**Device details (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS
 - Version 16.5

**Additional context**
https://developer.apple.com/forums/thread/127678

**Comment by ankurfyp20** [comment]
Getting the same error during uploading build on TestFlight.

**ITMS-90338: Non-public API usage -** The app references non-public symbols in Frameworks/AmazonIVSPlayer.framework/AmazonIVSPlayer: _CMTimebaseCreateWithMasterClock. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

**Comment by MrShiY** [comment]
+1

**Comment by Lunziyuan** [comment]
+1
<img width="1324" alt="image" src="https://github.com/aws-samples/amazon-ivs-player-ios-sample/assets/31342448/3d130e97-ac0c-4ec4-813b-ff80b2b6d88f">

**Comment by MuthuZEE** [comment]
+1

**Comment by profugocanis** [comment]
+1

**Comment by crazyfree** [comment]
+1

**Comment by paulnipu** [comment]
+1

**Comment by hvsw** [comment]
+1

---

We didn't update `AmazonIVSPlayer` since our last submission and we're having the same issue, so there was definitely a change in Apple's binary validation. I believe IVS will need to make some changes.

https://developer.apple.com/forums/thread/733318

**Comment by cemnisan** [comment]
+1

**Comment by gunyguni** [comment]
+1

**Comment by azeinn** [comment]
+1

**Comment by chenqihui** [comment]
+1

**Comment by xqpmjh** [comment]
+10086

**Comment by namdang94** [comment]
+1

**Comment by addbrick** [comment]
Update: From my amazon support contact. Apple and Amazon are working together on this. They understand the impact. Amazon is expecting Apple to revert their change. There is no timeline stated.

**Comment by ryanecrist** [comment]
Hello, thanks for filing an issue.

Due to a recent App Store policy change, the `CMTimebaseCreateWithSourceClock` API used by the AmazonIVSPlayer SDK is now being flagged as private and is blocking app store submissions.

IVS and Apple have determined that the issue is in Apple’s system and are actively working together to address the underlying issue.

Both IVS and Apple engineers understand the impact and urgency of the behavior and are working to resolve it as soon as possible. Apple is tracking this issue here https://developer.apple.com/system-status/. While we cannot provide the timelines for a fix, we expect Apple to revert the changes which in turn should resolve issues with app store submissions without any additional changes or patched releases from IVS.

With that being said, the IVS team will provide an update as soon as one is available.

Thanks all for your patience.

**Comment by ryanecrist** [comment]
The IVS team has confirmed that the fix pushed by Apple was successful and apps should now be able to be pushed to the App Store. The change by Apple means that no IVS SDK needs to be changed on the application side. 

Please let us know if there is any behavior when a attempting to release an app.

**Comment by hvsw** [comment]
This is back.

> App Store Connect
>
> Dear Developer,
> We identified one or more issues with a recent delivery for your app, "My app" 1.2.3 (4567). Please correct the following issues, then upload again.
>
> ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/AmazonIVSPlayer.framework/AmazonIVSPlayer: _CMTimebaseCreateWithMasterClock. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
>
> Best regards,
> The App Store Team

**Comment by ryanecrist** [comment]
Hi @hvsw, thanks for reaching out - we are currently investigating this issue. Can you assist our investigation by providing the following information?

1. When did you submit your app to Apple for review?
2. Does your app pass validation in Xcode now if you select the "Validate App" option in the Xcode Organizer window?

Thanks!

**Comment by JuliaGrasevych** [comment]
Hi! We're experiencing this issue with submission too.
1. We submitted the app at 07:57 GMT today and got a rejection.
2. We're using Fastlane to upload to TestFlight

**Comment by rahul-ios-779** [comment]
+1

**Comment by MrShiY** [comment]
+1

**Comment by hvsw** [comment]
@ryanecrist the first Invalid Binary rejection was at 10:19am Pacific. We got the same thing at 5:02pm and 9:08pm. We're using fastlane to submit.

**Comment by ryanecrist** [comment]
Thanks all we're in communication with Apple and will update this thread when we learn more. In the mean time if you haven't already we encourage you to file an issue using Feedback Assistant.

**Comment by esatp** [comment]
I'm unable to upload too, this is happening right now.
I updated to the latest versions of AmazonIVSPlayer and AmazonIVSBroadcast and still got the same error.
Xcode Version 14.3.1

![image](https://github.com/aws-samples/amazon-ivs-player-ios-sample/assets/3341832/527fd6bc-64e2-4a6a-8cec-2f946f984554)

**Comment by ryanecrist** [comment]
We have gotten confirmation from Apple that a change has been released to the App Store that resolves the issue. The IVS team has tested internally and it appears the behavior has been mitigated. As before this requires **no updates to the AmazonIVSPlayer** SDK.

Please let us know if you continue experiencing the behavior and we can inform the Apple team accordingly. Thanks all!
