### ISSUE TITLE
IVS Chat is not working

### ISSUE THREAD

**Issue by MuthuZEE** [aws-samples/amazon-ivs-player-ios-sample#53]
IVS Chat room is unable to connect

**Describe the bug**
We're using IVS SDK for Live Stream player and Chat functionality. After multiple iterations of the application with this solution working flawlessly. we recently encounter issue with chat functionality of IVS. To precise, This is encountered only after this issue. https://github.com/aws-samples/amazon-ivs-player-ios-sample/issues/51. Any clues around the fix would be helpful 

**To Reproduce**
IVS Chat Room connection is failing with **Unknown Error**
Error received
"**Problem connectng chat Room: Optional(\"A client or server connection was severed in the middle of an in-progress load.\") and code: Unknown error.**"

**Expected behavior**
IVS Chat Room should connect and be able to send/receive messages

**Screenshots**
If applicable, add screenshots to help explain your problem, e.g. of the player behavior you're seeing or debugger output.

**Device details (please complete the following information):**
 - Device: [e.g. iPhone 12 Pro]
 - Version [e.g. 12.5]

**Additional context**

**Comment by ryanecrist** [comment]
Hello, thanks for filing an issue.

This repo is not monitored for chat related issues.

If urgent troubleshooting or technical support is needed, please reach out to AWS Support via the AWS Support Center (https://docs.aws.amazon.com/awssupport/latest/user/getting-started.html).
